modded class LBConfigInfo {
	void LBConfigInfo() {
		RegisterClassComment("LBAdminAuditLogConfig", "Settings for the Admin Audit Log");
		RegisterClassVariableComment("LBAdminAuditLogConfig", "enabled", "Toggle if any audit logs should be written at all");
		RegisterClassVariableComment("LBAdminAuditLogConfig", "keepLogsTime", "Time in seconds until audit log entries are deleted. Default is 7 days");
		RegisterClassVariableComment("LBAdminAuditLogConfig", "loggedActions", "List of all AuditLog actions to enable/disable logging to only log what is needed");
		RegisterClassComment("LBAdminMenuSettings", "This configs contains basic settings for the admin menu behaviour (this should be edited ingame in the admin menu itself!)");
		RegisterClassVariableComment("LBAdminMenuSettings", "showPlayerInInvisible", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espFilters", "");
		RegisterClassVariableComment("LBESPFilter", "name", "");
		RegisterClassVariableComment("LBESPFilter", "items", "");
		RegisterClassVariableComment("LBESPFilter", "color", "");
		RegisterClassVariableComment("LBESPFilter", "active", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "itemspawnerCategories", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "itemspawnerCategoryNames", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "itemSpawnerDefaultSpawn", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "displayPlayerTagsInPlayerList", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "presetSpawnerCategory", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "teleportManagerCategory", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "alertJoinWatchlistLocal", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "alertJoinWatchlistServer", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "alertJoinWatchlistGlobal", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "frameColor", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "lastEspDistanceMode", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "lastEspDistance", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espShowClassnames", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espSkeletonHighDetail", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espSkeletonDrawJoints", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espSkeletonIgnoreDistance", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espSkeletonColor", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espSkeletonColorDead", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espJointsColor", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espEnableDrag", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espToSurface", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espDragCamera", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espMinHealth", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "espMaxHealth", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "freecamTurbo", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "freecamMouseSensitivity", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "freecamFOV", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "freecamMouseSmooth", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "freecamMovementSmooth", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "freecamAllowUnderground", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "freecamSpeed", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "freecamResetFOVOnEnter", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "freecamResetFOVOnLettingGo", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "itemMapListShowNames", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "itemMapListShowChildCount", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "objB_snap_ground", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "objB_snap_object", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "objB_camera_rotation", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "lookingAtCopyItemname", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "playerListSort", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "mapShowPlayers", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "mapShowVehicles", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "mapPlayerColor", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "mapVehicleColor", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "mapBoatColor", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "mapHeliColor", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "highlightedPlayerColor", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "watchlistLastCategory", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "banlistLastCategory", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "lookAtPositionFormat", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "lookAtPositionCustomFormat", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "lookAtDirectionFormat", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "lookAtDirectionCustomFormat", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "constructionEditorConfig", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "constructionEditorFaviourites", "");
		RegisterClassVariableComment("LBAdminMenuSettings", "lastCommands", "");
		RegisterClassComment("LBAdminMenuWindowConfig", "This config hold information about window stats including positions, size and other information specific to a window. This also contains window presets");
		RegisterClassVariableComment("LBAdminMenuWindowConfig", "selectedEntry", "");
		RegisterClassVariableComment("LBAdminMenuWindowConfig", "expanded", "");
		RegisterClassVariableComment("LBAdminMenuWindowConfig", "entries", "List of all Window states");
		RegisterClassVariableComment("array<ref LBAdminMenuWindowConfigEntry>", "windowClassname", "");
		RegisterClassVariableComment("array<ref LBAdminMenuWindowConfigEntry>", "windowX", "");
		RegisterClassVariableComment("array<ref LBAdminMenuWindowConfigEntry>", "windowY", "");
		RegisterClassVariableComment("array<ref LBAdminMenuWindowConfigEntry>", "windowW", "");
		RegisterClassVariableComment("array<ref LBAdminMenuWindowConfigEntry>", "windowH", "");
		RegisterClassVariableComment("array<ref LBAdminMenuWindowConfigEntry>", "pinned", "");
		RegisterClassVariableComment("array<ref LBAdminMenuWindowConfigEntry>", "visible", "");
		RegisterClassVariableComment("LBAdminMenuWindowConfig", "frameOrders", "");
		RegisterClassVariableComment("LBAdminMenuWindowConfig", "frameNames", "");
		RegisterClassComment("LBAdminToolsMainConfig", "this config contains some very basic settings");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "serverStatusWebhookInterval", "Interval in seconds the status webhook will be sent");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "addPossibleCheatersToWatchlist", "Enable this to automatically get players added to the server watchlist, who are potential cheaters");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "watchlistCheatDetections", "List of possible cheats detected and which should add a player to the watchlist");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "deleteDupedItemsOnLogin", "If duped items are detected on login (most common known dupe method), all duped items are deleted (original item is not deleted)");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "deleteDupedItemsOnServerRestart", "If the server detects a duped item on server restart, it will delete these duped items and will keep the original item");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "preventItemTeleportHacks", "Cheats can teleport any item including bases, items or any other item. Even buildings placed via the Editor. This will prevent these hacks from working");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "preventLootThroughWalls", "Additional checks when players try to loot containers through walls");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "validateActionOrigin", "Fixes an expoit in the vanilla action system allowing users to execute actions they should not be able to");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "validateActionDistance", "Fixes an expoit in the vanilla action system allowing users to execute some actions from very far away");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "preventIllegalMagazines", "Prevents players for abusing a bug allowing them to load anything as a weapon magazine");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "logInventoryEvents", "Log any inventory event for all players to the profiles:LBmaster_InvLog_TIMESTAMP.log");
		RegisterClassVariableComment("LBAdminToolsMainConfig", "contributeToGlobalBanlist", "This will add cheaters, which are 100% cheating automatically to a global CF Tools banlist. You can use the banlist by adding `c89df4f2-9162-4ab9-9d17-38f16ef0bf24` to your Banlists in CF Cloud");
		RegisterClassComment("LBBanManager", "Should not be edited manually, but only ingame through the admin menu");
		RegisterClassVariableComment("LBBanManager", "showRemainingTime", "Display the remaining time when a player is kicked");
		RegisterClassVariableComment("LBBanManager", "deleteExpiredBans", "Delete bans from the list or only set them to expired and keep the entries");
		RegisterClassVariableComment("LBBanManager", "bans", "list of banned players");
		RegisterClassVariableComment("LBBanEntry", "steamid", "Steamid of the player");
		RegisterClassVariableComment("LBBanEntry", "name", "Name of the player when he was banned");
		RegisterClassVariableComment("LBBanEntry", "bannedBy", "Steamid of the admin, who banned the player");
		RegisterClassVariableComment("LBBanEntry", "bannedByName", "Name of the admin, who banned the player at the time of the ban");
		RegisterClassVariableComment("LBBanEntry", "bannedTimestamp", "Unix timestamp when the ban was issued");
		RegisterClassVariableComment("LBBanEntry", "duration", "Duration in seconds of the ban. -1 for permanent bans");
		RegisterClassVariableComment("LBBanEntry", "reason", "Reason of the ban, set by the admin");
		RegisterClassVariableComment("LBBanEntry", "comment", "Internal comment (only visible to admins)");
		RegisterClassComment("LBForbidenItemsList", "contains items, which cannot be spawned by admin");
		RegisterClassVariableComment("LBForbidenItemsList", "forbiddenItems", "List of itemnames, which cannot be spawned by admins, who don't have the \"admin.ignore.forbidden_items\" permission");
		RegisterClassComment("LBGlobalBanManager", "Here you can enable / disable if the server should use the \"global\" banlist system\nGlobal means all the servers running this Admin Tools license will share one banlist\nAdding someone to the banlist will sync the ban to all servers within a maximum on 1 minute delay");
		RegisterClassVariableComment("LBGlobalBanManager", "enabled", "Enable / Disable if this server should use the global banlist");
		RegisterClassVariableComment("LBGlobalBanManager", "bans", "All entries on the global banlist (editing this will not change anything since the data is not saved here and only for cases where to banlist system cannot be reached)");
		RegisterClassVariableComment("LBBanEntry", "steamid", "Steamid of the player");
		RegisterClassVariableComment("LBBanEntry", "name", "Name of the player when he was banned");
		RegisterClassVariableComment("LBBanEntry", "bannedBy", "Steamid of the admin, who banned the player");
		RegisterClassVariableComment("LBBanEntry", "bannedByName", "Name of the admin, who banned the player at the time of the ban");
		RegisterClassVariableComment("LBBanEntry", "bannedTimestamp", "Unix timestamp when the ban was issued");
		RegisterClassVariableComment("LBBanEntry", "duration", "Duration in seconds of the ban. -1 for permanent bans");
		RegisterClassVariableComment("LBBanEntry", "reason", "Reason of the ban, set by the admin");
		RegisterClassVariableComment("LBBanEntry", "comment", "Internal comment (only visible to admins)");
		RegisterClassComment("LBLastCheatsConfig", "This config contains information about the last cheats enabled by the admin. They can be restored when needed");
		RegisterClassVariableComment("LBLastCheatsConfig", "saveLevel", "If or when the settings should be restored");
		RegisterClassVariableComment("LBLastCheatsConfig", "lastServer", "IP:Port of the last connected server to know if the player relogged");
		RegisterClassVariableComment("LBLastCheatsConfig", "full_bright", "If full bright was enabled");
		RegisterClassVariableComment("LBLastCheatsConfig", "enabledModifiers", "Other enabled Player Modifiers");
		RegisterClassComment("LBPositionsListPrivate", "");
		RegisterClassVariableComment("LBPositionsListPrivate", "positionsPerMap", "List of all positions per map");
		RegisterClassComment("LBPositionsListServer", "Should not be edited manually, but only ingame through the admin menu");
		RegisterClassVariableComment("LBPositionsListServer", "positions", "List of all positions saved on the server");
		RegisterClassVariableComment("LB_TeleportPos", "name", "Name of the position");
		RegisterClassVariableComment("LB_TeleportPos", "pos", "x,y,z of the position");
		RegisterClassVariableComment("LB_TeleportPos", "dir", "Direction the player will look to when teleported");
		RegisterClassVariableComment("LB_TeleportPos", "addedBy", "Steamid of the admin, who added the position");
		RegisterClassComment("LBWatchlistGlobal", "This file contains the current global watchlist. This file is automatically overwritten by the server when changes are detected");
		RegisterClassVariableComment("LBWatchlistGlobal", "entries", "List of all players on the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "steamid", "Steamid of the player");
		RegisterClassVariableComment("LBWatchlistEntry", "name", "Name of the player at the time of being added to the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "addedDate", "Unix timestamp when the player was added");
		RegisterClassVariableComment("LBWatchlistEntry", "lastModified", "Unix timestamp when the entry was last edited");
		RegisterClassVariableComment("LBWatchlistEntry", "addedBySteamid", "Steamid of the admin, who added the player to the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "addedByName", "Name of the admin at the time of adding the player");
		RegisterClassVariableComment("LBWatchlistEntry", "reason", "Reason the player was added to the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "confidence", "value between 0.0 and 1.0 to indicate how confident the admin is, that the player is duping, cheating, trolling etc.");
		RegisterClassVariableComment("LBWatchlistEntry", "message", "Field for the admins to take further notes on the player");
		RegisterClassComment("LBWatchlistLocal", "");
		RegisterClassVariableComment("LBWatchlistLocal", "entries", "List of all players on the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "steamid", "Steamid of the player");
		RegisterClassVariableComment("LBWatchlistEntry", "name", "Name of the player at the time of being added to the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "addedDate", "Unix timestamp when the player was added");
		RegisterClassVariableComment("LBWatchlistEntry", "lastModified", "Unix timestamp when the entry was last edited");
		RegisterClassVariableComment("LBWatchlistEntry", "addedBySteamid", "Steamid of the admin, who added the player to the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "addedByName", "Name of the admin at the time of adding the player");
		RegisterClassVariableComment("LBWatchlistEntry", "reason", "Reason the player was added to the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "confidence", "value between 0.0 and 1.0 to indicate how confident the admin is, that the player is duping, cheating, trolling etc.");
		RegisterClassVariableComment("LBWatchlistEntry", "message", "Field for the admins to take further notes on the player");
		RegisterClassComment("LBWatchlistServer", "Should not be edited manually, but only ingame through the admin menu");
		RegisterClassVariableComment("LBWatchlistServer", "entries", "List of all players on the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "steamid", "Steamid of the player");
		RegisterClassVariableComment("LBWatchlistEntry", "name", "Name of the player at the time of being added to the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "addedDate", "Unix timestamp when the player was added");
		RegisterClassVariableComment("LBWatchlistEntry", "lastModified", "Unix timestamp when the entry was last edited");
		RegisterClassVariableComment("LBWatchlistEntry", "addedBySteamid", "Steamid of the admin, who added the player to the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "addedByName", "Name of the admin at the time of adding the player");
		RegisterClassVariableComment("LBWatchlistEntry", "reason", "Reason the player was added to the watchlist");
		RegisterClassVariableComment("LBWatchlistEntry", "confidence", "value between 0.0 and 1.0 to indicate how confident the admin is, that the player is duping, cheating, trolling etc.");
		RegisterClassVariableComment("LBWatchlistEntry", "message", "Field for the admins to take further notes on the player");
		RegisterClassComment("LBWeatherManagerConfig", "");
		RegisterClassVariableComment("LBWeatherManagerConfig", "timePresets", "");
		RegisterClassVariableComment("LBNamedTimePreset", "year", "");
		RegisterClassVariableComment("LBNamedTimePreset", "name", "");
		RegisterClassVariableComment("LBWeatherManagerConfig", "weatherPresets", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "overcast", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "rain", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "snowfall", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "fog", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "volFogDensity", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "volFogHeight", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "volFogBias", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "windMag", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "windDir", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "defaultTime", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "defaultDuration", "");
		RegisterClassVariableComment("LBNamedWeatherPreset", "name", "");
		RegisterClassComment("LBAdminItemPresetConfig", "Should not be edited manually, but only ingame through the admin menu");
		RegisterClassVariableComment("LBAdminItemPresetConfig", "presets", "List of all saved presets;");
		RegisterClassVariableComment("LBAdminItemPresetItem", "itemname", "Itemname of the spawned item");
		RegisterClassVariableComment("LBAdminItemPresetItem", "spawnIn", "0 = spawn in any, 1 = spawn in cargo, 2 = spawn as attachment");
		RegisterClassVariableComment("LBAdminItemPresetItem", "foodStage", "Number of the food stage or if it can hold liquid, the liquid type");
		RegisterClassVariableComment("LBAdminItemPresetItem", "quantity", "Quantity of the item in Percent (0.0 = 0%, 1.0 = 100%)");
		RegisterClassVariableComment("LBAdminItemPresetItem", "health", "Health of the item in Percent");
		RegisterClassVariableComment("LBAdminItemPresetItem", "debugSpawn", "set to 1 to call the OnDebugSpawn() method after object was spawned");
		RegisterClassVariableComment("LBAdminItemPresetItem", "ceSpawn", "Set to 1 to spawn the item with the Central Economy presets");
		RegisterClassVariableComment("LBAdminItemPresetItem", "children", "Items spawned as children on this item");
		RegisterClassComment("LBAdminItemPresetConfigServer", "Should not be edited manually, but only ingame through the admin menu");
		RegisterClassVariableComment("LBAdminItemPresetConfigServer", "presets", "All presets saved on the server");
		RegisterClassVariableComment("LBAdminItemPresetItem", "itemname", "Itemname of the spawned item");
		RegisterClassVariableComment("LBAdminItemPresetItem", "spawnIn", "0 = spawn in any, 1 = spawn in cargo, 2 = spawn as attachment");
		RegisterClassVariableComment("LBAdminItemPresetItem", "foodStage", "Number of the food stage or if it can hold liquid, the liquid type");
		RegisterClassVariableComment("LBAdminItemPresetItem", "quantity", "Quantity of the item in Percent (0.0 = 0%, 1.0 = 100%)");
		RegisterClassVariableComment("LBAdminItemPresetItem", "health", "Health of the item in Percent");
		RegisterClassVariableComment("LBAdminItemPresetItem", "debugSpawn", "set to 1 to call the OnDebugSpawn() method after object was spawned");
		RegisterClassVariableComment("LBAdminItemPresetItem", "ceSpawn", "Set to 1 to spawn the item with the Central Economy presets");
		RegisterClassVariableComment("LBAdminItemPresetItem", "children", "Items spawned as children on this item");
	}
}