modded class LBConfigInfo {
	void LBConfigInfo() {
		RegisterClassComment("ChatConfig", "**Disable with LBmaster_GroupDisableChat.pbo** If you want to use your own Chat Mod");
		RegisterClassVariableComment("ChatConfig", "displayGroupTagsInfrontOfName", "enable / disable if group Tags should be displayed infront of the Playername in chat. (Each Group Leader can decide to hide their tag too)");
		RegisterClassVariableComment("ChatConfig", "forceDisplayGroupTagsInChat", "Set to 1 so Group Leaders cannot disable that their Group Tag is hidden in chat");
		RegisterClassVariableComment("ChatConfig", "enableMuteVote", "Enable if players should be able to vote if another player should be muted");
		RegisterClassVariableComment("ChatConfig", "muteVoteMinPlayers", "Min Players online for a vote to begin");
		RegisterClassVariableComment("ChatConfig", "muteVoteMuteTimeMins", "time a player should be muted if the vote was successful");
		RegisterClassVariableComment("ChatConfig", "muteVotePercentile", "Percentile of players, that need to vote for the player (0 = 0%, 0.5 = 50%, 1.0 = 100%)");
		RegisterClassVariableComment("ChatConfig", "channels", "All channels available");
		RegisterClassVariableComment("ChannelCfg", "channelName", "Name of the Channel displayed when switching channels and when opening the chat");
		RegisterClassVariableComment("ChannelCfg", "channelColor", "Color of the Playername in the Chat (argb colors from 0 to 255 for Alpha, Red, Green and Blue Channel)");
		RegisterClassVariableComment("ChannelCfg", "canReceiveMessagesFromPlayers", "Enable / Disable if any player can write in this channel or the channel should be used by a mod and messages can only be sent via script");
		RegisterClassVariableComment("ChannelCfg", "writeChannelPermission", "Permission needed to write in this channel. Empty string = everyone can write");
		RegisterClassVariableComment("ChannelCfg", "readChannelPermission", "Permission needed to read this channel. Empty string = everyone can read");
		RegisterClassVariableComment("ChannelCfg", "globalChannel", "set to 1 if Channel is a global channel");
		RegisterClassVariableComment("ChannelCfg", "groupChannel", "set to 1 if Channel is a group channel");
		RegisterClassVariableComment("ChannelCfg", "directChannel", "set to 1 if Channel is a direct (proximity) channel");
		RegisterClassVariableComment("ChannelCfg", "defaultChannel", "set to 1 if this is the default channel selected when the player joins");
		RegisterClassVariableComment("ChannelCfg", "applyChatFilter", "set to 1 if this channel should be filtered by the bad words filter if it's enabled");
		RegisterClassVariableComment("ChannelCfg", "slowModeSecondsBetweenMessages", "Time players need to wait to send another message");
		RegisterClassVariableComment("ChannelCfg", "muted", "When set to 1, this channel is currently muted and only admins can write in the channel");
		RegisterClassVariableComment("ChatConfig", "colorBattleyeMessage", "argb Color for Battleye messages (e.g. RCON / Server Messages from CF Tools)");
		RegisterClassVariableComment("ChatConfig", "prefixGroups", "List of custom prefixes for players (e.g. Admins)");
		RegisterClassVariableComment("PrefixGroup", "prefix", "text infront of the playername (adding a tailing space is recommended)");
		RegisterClassVariableComment("PrefixGroup", "colorR", "Red Channel Color from 0 to 255");
		RegisterClassVariableComment("PrefixGroup", "colorG", "Green Channel Color from 0 to 255");
		RegisterClassVariableComment("PrefixGroup", "colorB", "Blue Channel Color from 0 to 255");
		RegisterClassVariableComment("PrefixGroup", "members", "List of all Steamids, which should be in this group");
		RegisterClassVariableComment("PrefixGroup", "permissionToApplyGroup", "Permission, which can be added to the [Admins.json](index.php?id=83) to automatically assign this prefix for that admin");
		RegisterClassVariableComment("ChatConfig", "badWords", "List of all Bad words, which should be censored. (Not Casesensitive)");
		RegisterClassVariableComment("ChatConfig", "enabledBadWordsCensor", "enable / disable if Bad Words should be censored / punished with chat mute");
		RegisterClassVariableComment("ChatConfig", "blockBadWordContainingMessages", "enable / disable if the message should be sent even if bad words were detected");
		RegisterClassVariableComment("ChatConfig", "badWordsBlockedMessage", "message sent to the user when bad words were detected");
		RegisterClassVariableComment("ChatConfig", "badWordsMuteTime", "Time in minutes the player will be muted if bad words were detected");
		RegisterClassComment("LB_NoBuildConfig", "This file contains a list of all no build zones and some additional settings like if they should be displayed on the map, which color the markers should have and if certain items can still be placed in no build zones (for example Traps)\n\nThe ingame Admin menu allows you to change almost all of these settings and add and remove no build zones, so check out the ingame admin menu too!");
		RegisterClassVariableComment("LB_NoBuildConfig", "enabled", "Enabled (1) or Disable (0) the whole system");
		RegisterClassVariableComment("LB_NoBuildConfig", "displayOnMap", "Set to 1 if players can see the zones on the map (they can turn them off in the client settings to hide them). Or set it to 0 to hide all zones for all players. No player will be able to enable the zones for them then");
		RegisterClassVariableComment("LB_NoBuildConfig", "notificationTitle", "Title of the notification when a player cannot build there");
		RegisterClassVariableComment("LB_NoBuildConfig", "notificationMessage", "The text of the notification. `{pos}` will be replaced with the name of the current Zone the player is in");
		RegisterClassVariableComment("LB_NoBuildConfig", "ignoreItems", "Items which can be placed inside of No Build Zones. For example Traps. You can enter Baseclasses like Trap_Base here. Be aware, that you need to enter the name of the config.cpp class, which is `Trap_Base` and not `TrapBase`");
		RegisterClassVariableComment("LB_NoBuildConfig", "circleColorR", "Red Color of the Circles shown on the map");
		RegisterClassVariableComment("LB_NoBuildConfig", "circleColorG", "Green Color of the Circles shown on the map");
		RegisterClassVariableComment("LB_NoBuildConfig", "circleColorB", "Blue Color of the Circles shown on the map");
		RegisterClassVariableComment("LB_NoBuildConfig", "zones", "List of all no build zones");
		RegisterClassVariableComment("LB_NoBuildEntry", "name", "Name of this position. This will replace the `{pos}` placeholder when sending the error message to the player");
		RegisterClassVariableComment("LB_NoBuildEntry", "x", "X position of the Zone");
		RegisterClassVariableComment("LB_NoBuildEntry", "y", "Y position (or rather the Z coordinate) of the Zone");
		RegisterClassVariableComment("LB_NoBuildEntry", "r", "Radius of the Zone");
		RegisterClassComment("LBAirdropSettingsExpansion", "When you have expansion Missions / Expansion Airdrops installed, this config will be generated\nHere you can change the settings for Expansions Airdrop Markers for Advanced Groups");
		RegisterClassVariableComment("LBAirdropSettingsExpansion", "createMarker", "Enable / Disable if markers should be added to the map. You might need to enable the Marker in the expansion config somewhere");
		RegisterClassVariableComment("LBAirdropSettingsExpansion", "markerName", "Default Marker name. Will be replaced with the container name when ShowAirdropTypeOnMarker is enabled in the expansion settings");
		RegisterClassVariableComment("LBAirdropSettingsExpansion", "markerIcon", "Path of the icon to use for the Airdrop marker");
		RegisterClassVariableComment("LBAirdropSettingsExpansion", "color", "Color of the Airdrop Marker");
		RegisterClassComment("LBClanTagColorConfig", "This file keeps track of which players have permissions to update clan tag colors.\n\nIf a player updates a tag color, the color will be applied until no player in the group is left with this permission.\n\nThis ensures players don't join groups to give them a clan tag and then leaving again");
		RegisterClassVariableComment("LBClanTagColorConfig", "deleteEmptyUses", "enable this option to automatically delete entries, which reached 0 remaining uses");
		RegisterClassVariableComment("LBClanTagColorConfig", "authorizedPlayers", "A simple list of Steamids, which can change clan tag color");
		RegisterClassVariableComment("LBClanTagColorConfigEntry", "steamid", "Steamid of the player");
		RegisterClassVariableComment("LBClanTagColorConfigEntry", "comment", "Comment to find player entries easily");
		RegisterClassVariableComment("LBClanTagColorConfigEntry", "remainingCount", "Remaining count of how often they can change the tag color. -1 for infinite");
		RegisterClassComment("LBFOWConfig", "This configs allows you to configure the basics of the Fog of War feature\nTo change how markers are displayed when hidden by the Fog of War, check the Marker Settings");
		RegisterClassVariableComment("LBFOWConfig", "enabled", "Enable / disable the whole Fog of War feature");
		RegisterClassVariableComment("LBFOWConfig", "hideCursorCoordinates", "Show ?? ?? instead of the correct coordinates on the info page when hovering over an unrevealed area");
		RegisterClassVariableComment("LBFOWConfig", "canAddMarkers", "Can add markers in unrevealed areas. This could be abused when enabled depeding on your marker settings, but generally it's recommended to not allow players to place down markers");
		RegisterClassVariableComment("LBFOWConfig", "hideServerMarkersInList", "Hide server markers in the Markers list when they are not revealed yet");
		RegisterClassVariableComment("LBFOWConfig", "hideGroupMarkersInList", "Hide group markers in the Markers list when they are not revealed yet");
		RegisterClassVariableComment("LBFOWConfig", "hidePrivateMarkersInList", "Hide private markers in the Markers list when they are not revealed yet");
		RegisterClassVariableComment("LBFOWConfig", "sectorCount", "Amount of sectors per x and y axis. The total count is the value squared. So 200 would be 200 * 200 = 40000 sectors total. Due to render limits and performance concerns, this value is capped at 200 sectors. It's mostly useful if you run smaller maps and want less sectors. Be aware, that changing this will break the current players revealed areas as the coordinates change!!");
		RegisterClassVariableComment("LBFOWConfig", "discoveryRadius", "Radius in Meter around the player where any touching sector is discovered. 0 means the player only discovers sectors he really entered. Anything else check if the sectors around the player intersect the circle around the player with this radius set here. Be aware, that a bigger radius means more checks for the client!");
		RegisterClassVariableComment("LBFOWConfig", "fogColor", "Color of the fog. Make sure to set the Alpha value to maximum (255), otherwise players can see the map through the fog");
		RegisterClassVariableComment("LBFOWConfig", "drawMapGridOverFog", "Enable to draw the grid lines over the FOW to make it easier for players to see what is going on");
		RegisterClassVariableComment("LBFOWConfig", "overwriteColorFromConfig", "Overwrite the grid lines color or use the color from the RscMapControl config.cpp class");
		RegisterClassVariableComment("LBFOWConfig", "gridColorOverwrite", "The color the grid should have if overwritten");
		RegisterClassVariableComment("LBFOWConfig", "centerOnPlayerIfNotOnScreen", "Move the map to the player position if hw is not on screen already, so players don't have to search for their player in the Fog");
		RegisterClassComment("LBFOWPlayerInfo", "This file contains information about which sectors a player already discovered");
		RegisterClassVariableComment("LBFOWPlayerInfo", "fowSectorInfo", "List of sectors in a binary format. Starting at sector 0,0 row wise and bit encoded");
		RegisterClassVariableComment("LBFOWPlayerInfo", "sectorCount", "Last sector count (only used to sync with client and overwritten on load)");
		RegisterClassVariableComment("LBFOWPlayerInfo", "sectorSize", "Last sector size based on the world size (only used to sync with client and overwritten on load)");
		RegisterClassVariableComment("LBFOWPlayerInfo", "discoveryRadius", "Last discovery Radius (only used to sync with client and overwritten on load)");
		RegisterClassComment("LBGroupLevels", "This file contains all possible group levels. The levels must start at 0 and must not have any gaps ! So after level 0 is level 1, then 2, then 3. If you remove level 2, then groups cannot be upgraded to level 3 anymore, because level 2 does not exist ! You could abuse this system to add an unreachable level and set that level for your Admins group to have higher limits, that normal groups.");
		RegisterClassVariableComment("LBGroupLevels", "levels", "List of all levels. Make sure there is a level with leve 0 and the levels have subgroups if you have subgroups enabled in the group settings");
		RegisterClassVariableComment("LBGroupLevel", "level", "current level number (starts with 0. Do not use the same for different levels and do not skip numbers)");
		RegisterClassVariableComment("LBGroupLevel", "maxPlayerCount", "Maximum Total Player Count");
		RegisterClassVariableComment("LBGroupLevel", "upgradeCost", "Cost to upgrade the group to this level (`upgradeCost` for level 0 will be the creation cost of the group)");
		RegisterClassVariableComment("LBGroupLevel", "subgroups", "List of subgroups with their size and if they are offline subgroups");
		RegisterClassVariableComment("LBGroupLevelSubgroupInfo", "size", "Max amount of players that can be in this subgroup. This does not affect how many players in total can join the group. That is defined by the maxPlayerCount in the GroupLevels.json file. Make sure the total size of all subgroups is enough for all players to fit in");
		RegisterClassVariableComment("LBGroupLevelSubgroupInfo", "offlineOnly", "Only for offline players. Will automatically move players into the subgroup when enabled and enough space is left in the subgroup!");
		RegisterClassVariableComment("LBGroupLevelSubgroupInfo", "nameOverride", "Overwrite the default subgroup name");
		RegisterClassVariableComment("LBGroupLevel", "groupMarkerLimitAdded", "Group Marker Limit added to the `groupMarkerLimit` in the MainConfig.json");
		RegisterClassVariableComment("LBGroupLevel", "groupPingsLimitAdded", "Added amount of Pings per player since players can set multiple pings");
		RegisterClassVariableComment("LBGroupLevel", "groupPlotpolesLimitAdded", "If Plotpole DLC is used: Max Count of Plotpoles adding to the base Limit `defaultPlotpoleCountPerGroup` in PlotpoleConfig.json");
		RegisterClassComment("LBGroupMiscConfig", "This is the Misc Config of the Advanced Groups Mod. You can tweak a lot of things here, but these are the most important settings you find in this file:\n\n- Map Legend to have a small Legend on the Map explaining different icons to make the Map a bit more clean and better to read\n\n- Compass, GPS (Minimap) Settings\n\n- And more, just read through the settings if you find anything interesting");
		RegisterClassVariableComment("LBGroupMiscConfig", "enableMapLegend", "Show the Map legend in the bottom right to make the map less cluttered with markers, which are placed a lot on the map");
		RegisterClassVariableComment("LBGroupMiscConfig", "mapLegendTitle", "Title which is displayed on the Map Legend");
		RegisterClassVariableComment("LBGroupMiscConfig", "mapLegend", "List of entries, which will be displayed on the Map Legend. The order will be the same as in this list");
		RegisterClassVariableComment("MapLegendItem", "iconPath", "Path to the icon, which is displayed for this entry (Check the `availableIcons` list for icons you can use)");
		RegisterClassVariableComment("MapLegendItem", "iconColorA", "Alpha Color of the Icon");
		RegisterClassVariableComment("MapLegendItem", "iconColorR", "Red Color of the Icon");
		RegisterClassVariableComment("MapLegendItem", "iconColorG", "Green Color of the Icon");
		RegisterClassVariableComment("MapLegendItem", "iconColorB", "Blue Color of the Icon");
		RegisterClassVariableComment("MapLegendItem", "name", "Name displayed on the Map Legend");
		RegisterClassVariableComment("MapLegendItem", "nameColorA", "Alpha Color of the Text");
		RegisterClassVariableComment("MapLegendItem", "nameColorR", "Red Color of the Text");
		RegisterClassVariableComment("MapLegendItem", "nameColorG", "Green Color of the Text");
		RegisterClassVariableComment("MapLegendItem", "nameColorB", "Blue Color of the Text");
		RegisterClassVariableComment("LBGroupMiscConfig", "enableCompassHud", "enable / disable the compass at the top of the Players screen");
		RegisterClassVariableComment("LBGroupMiscConfig", "compassRequireItem", "make the Compass require an ingame item (like a compass or similar items)");
		RegisterClassVariableComment("LBGroupMiscConfig", "compassItems", "List of items counting as a compass item. (only one of the items in the list is needed. Not all together)");
		RegisterClassVariableComment("LBGroupMiscConfig", "enableGPS", "enable / disable the GPS (due to the implementation of the DayZ Map, this will reduce the Client FPS noticable if shown. Players can still disable the GPS in their Client Config)");
		RegisterClassVariableComment("LBGroupMiscConfig", "gpsDisplayAngle", "Display the Angle the Player is looking to on the GPS");
		RegisterClassVariableComment("LBGroupMiscConfig", "gpsDisplaySpeed", "Display the current Speed of the Player on the GPS");
		RegisterClassVariableComment("LBGroupMiscConfig", "gpsDisplayCoords", "Display the current Coordinates on the GPS");
		RegisterClassVariableComment("LBGroupMiscConfig", "gpsRequireItem", "Require the player to have an item in their inventory to enable the GPS");
		RegisterClassVariableComment("LBGroupMiscConfig", "gpsOnlyInVehicles", "Force the GPS only to show if the Player is in a vehicle and never outside of vehicles");
		RegisterClassVariableComment("LBGroupMiscConfig", "vehiclesWithGPS", "List of vehicle with an \"inbuild GPS\" (do not require the GPS Item if needed)");
		RegisterClassVariableComment("LBGroupMiscConfig", "gpsItems", "Items that count as a GPS (only one of the items in the list is needed. Not all together)");
		RegisterClassVariableComment("LBGroupMiscConfig", "mapRequireItem", "Require the player to have an item in their inventory to see the map. Otherwise the text below is displayed instead of the map and markers cannot be added or removed from the map");
		RegisterClassVariableComment("LBGroupMiscConfig", "mapItems", "Items that count as a Map (only one of the items in the list is needed. Not all together)");
		RegisterClassVariableComment("LBGroupMiscConfig", "mapNotFoundText", "Text, which is displayed when `mapRequireItem` is enabled and the player does not have any of the items listed in `mapItems`");
		RegisterClassVariableComment("LBGroupMiscConfig", "mapNotFoundImage", "Path to the image displayed together with the `mapNotFoundText`");
		RegisterClassVariableComment("LBGroupMiscConfig", "disableMapMenu", "Disable the whole map menu opened with M / P");
		RegisterClassComment("LBGroupPermissions", "List of all Permission Groups / Ranks for the Clan (default: Temp, Trial, Member, Admin, Leader)\n\nAll Groups will inherit the permissions from the inherit Group, so if an admin can invite a player, Leaders automatically can invite players too.\n\nPromote powers or other powers will at least be the same power as the inherit group and can never be lower.");
		RegisterClassVariableComment("LBGroupPermissions", "allGroups", "List of all permissions / ranks for the groups");
		RegisterClassVariableComment("LBGroupPermission", "UID", "Unique ID of this Rank (will be used to store the current Rank of the Player in the Groups json File)");
		RegisterClassVariableComment("LBGroupPermission", "nextGroupUID", "UID of the higher group (-1 if highest Rank)");
		RegisterClassVariableComment("LBGroupPermission", "previousGroupUID", "UID of the lower group (-1 if lowest Rank)");
		RegisterClassVariableComment("LBGroupPermission", "inheritGroupUID", "UID of the Rank, this Rank should inherit from (in most cases the `previousGroupUID`)");
		RegisterClassVariableComment("LBGroupPermission", "permName", "Displayname of the Rank shown behind the Playername in the Group overview");
		RegisterClassVariableComment("LBGroupPermission", "markerPermissions", "List of all Permissions for each Marker Type (see MainConfig.json):\n\n	- `param1`: type of the Marker (refer to MainConfig.json for all types available)\n\n	- `param2`: 0 if not visible / 1 if visible\n\n");
		RegisterClassVariableComment("LBGroupPermission", "canUpgrade", "enable / disable if the Player can Upgrade the Group to the next level");
		RegisterClassVariableComment("LBGroupPermission", "canPromote", "enable / disable if the Player can Promote others");
		RegisterClassVariableComment("LBGroupPermission", "canDemote", "enable / disable if the Player can Demote others");
		RegisterClassVariableComment("LBGroupPermission", "canInvite", "allow the Player to invite new Players to the Group");
		RegisterClassVariableComment("LBGroupPermission", "promotePower", "Power the Player has to promote others. Needs to be greater than the `promoteNeedPower` of the target rank of the promoted player");
		RegisterClassVariableComment("LBGroupPermission", "demotePower", "Power the player has to demote others. Needs to be greater than the `demoteNeedPower` of the current rank of the demoted player");
		RegisterClassVariableComment("LBGroupPermission", "moveSubgroupPower", "Power the player has to move others to a different subgroup. Needs to be greater than the `moveSubgroupNeedPower` of the current rank of the moved player");
		RegisterClassVariableComment("LBGroupPermission", "promoteNeedPower", "Power needed to promote someone to this rank");
		RegisterClassVariableComment("LBGroupPermission", "demoteNeedPower", "Power needed to demote someone from this rank to a lower rank");
		RegisterClassVariableComment("LBGroupPermission", "moveSubgroupNeedPower", "Power needed to move the player to a different subgroup");
		RegisterClassVariableComment("LBGroupPermission", "canChangeChatTagColor", "Allow the player to change the Chat Tag color if he is added to the `ClanTagColorChangePermissions.json` file. He needs to have both permissions");
		RegisterClassVariableComment("LBGroupPermission", "canDoBasebuilding", "Allow the player to build / dismandle / destroy Basebuilding items");
		RegisterClassVariableComment("LBGroupPermission", "canLowerFlag", "Allow the player to lower territory flags");
		RegisterClassVariableComment("LBGroupPermission", "canRaiseFlag", "Allow the player to raise territory flags");
		RegisterClassVariableComment("LBGroupPermission", "canPackPlotpole", "can destroy the Flagpole owned by the Group");
		RegisterClassVariableComment("LBGroupPermission", "canCreateSeeATMAccount", "(only with ATM DLC) can see the Balance of the Group Account");
		RegisterClassVariableComment("LBGroupPermission", "canCreateGroupATMAccount", "Can buy the Group account");
		RegisterClassVariableComment("LBGroupPermission", "canWithdrawGroupMoney", "Can withdraw money from the group account");
		RegisterClassVariableComment("LBGroupPermission", "canDepositGroupMoney", "Can deposit money to the group account");
		RegisterClassVariableComment("LBGroupPermission", "canOpenGroupGarage", "Can open the Group Garage when combined with the [Virtual Garage Mod](/product.php?id=5)");
		RegisterClassVariableComment("LBGroupPermission", "tempGroup", "if players in this group should be removed after server restart. 0 if group is persistent");
		RegisterClassComment("LBGroupTimeoutConfig", "Config that handles the group swap timeouts so player do not swap groups to gain advantages (disabled by default). Current timeouts are saved in the TimeoutPlayers.json");
		RegisterClassVariableComment("LBGroupTimeoutConfig", "enableTimeout", "Set to 1 to enable the timeouts");
		RegisterClassVariableComment("LBGroupTimeoutConfig", "timeoutDifferentGroupDurationSeconds", "Time in seconds a player needs to wait until he can join a different group than his last group (The timer will start when the player joined the first group and not when he left)");
		RegisterClassVariableComment("LBGroupTimeoutConfig", "timeoutSameGroupDurationSeconds", "Time in seconds a player needs to wait until he can join the same group he was in before (The timer starts when he joins the first group)");
		RegisterClassComment("LBMarkerSettingsConfig", "This config handles all Marker related settings. From visibility of markers, over max distance to death marker settings. Everything is handled here");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "canSeeOwnPlayerOnMap", "enable / disable if players should be able to see their own position on the map");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "requireItemToSeeOwnPlayerOnMap", "Enable if a player needs an item from the list below in their inventory too see their own marker on the map");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "ownPlayerMarkerItems", "One of the items is required in the inventory if an item is required to see yourself on the map");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "markerConfig", "Config for all Marker Types available:");
		RegisterClassVariableComment("MarkerConfigEntry", "type", "Type of the Marker Config. 0 = Static Marker (persistent), 1 = Dynamic Marker (deleted after server restart), 2 = Ping Marker, 3 = Group Marker, 4 = Group Player Marker, 5 = Private Marker");
		RegisterClassVariableComment("MarkerConfigEntry", "typeString", "String represenation of the Type. The important thing is the type above");
		RegisterClassVariableComment("MarkerConfigEntry", "maxDistance", "Maximum Distance the Marker Type will be visible in 3D and on the Compass");
		RegisterClassVariableComment("MarkerConfigEntry", "display3d", "enable / disable if the Marker Type is Visible in 3D");
		RegisterClassVariableComment("MarkerConfigEntry", "displayDistance", "enable / disable if the Marker Type should have a distance displayed in 3D");
		RegisterClassVariableComment("MarkerConfigEntry", "displayMap", "enable / disable if the Marker Type is Visible on the Map");
		RegisterClassVariableComment("MarkerConfigEntry", "displayCompass", "enable / disable if the Marker Type is Visible on the Compass");
		RegisterClassVariableComment("MarkerConfigEntry", "displayGPS", "enable / disable if the Marker Type is Visible on the GPS");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "markerConfigFOW", "Config for all Marker Types available when the marker is inside FOW:");
		RegisterClassVariableComment("MarkerConfigEntry", "type", "Type of the Marker Config. 0 = Static Marker (persistent), 1 = Dynamic Marker (deleted after server restart), 2 = Ping Marker, 3 = Group Marker, 4 = Group Player Marker, 5 = Private Marker");
		RegisterClassVariableComment("MarkerConfigEntry", "typeString", "String represenation of the Type. The important thing is the type above");
		RegisterClassVariableComment("MarkerConfigEntry", "maxDistance", "Maximum Distance the Marker Type will be visible in 3D and on the Compass");
		RegisterClassVariableComment("MarkerConfigEntry", "display3d", "enable / disable if the Marker Type is Visible in 3D");
		RegisterClassVariableComment("MarkerConfigEntry", "displayDistance", "enable / disable if the Marker Type should have a distance displayed in 3D");
		RegisterClassVariableComment("MarkerConfigEntry", "displayMap", "enable / disable if the Marker Type is Visible on the Map");
		RegisterClassVariableComment("MarkerConfigEntry", "displayCompass", "enable / disable if the Marker Type is Visible on the Compass");
		RegisterClassVariableComment("MarkerConfigEntry", "displayGPS", "enable / disable if the Marker Type is Visible on the GPS");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "addPlayerDeathMarker", "enable / disable if Death Markers should be added at the Death position of a player");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "deathMarkerPrivate", "enable / disable if the Death Marker should be added as a private Marker");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "deathMarkerGroup", "enable / disable if the Death Marker should be added as a group Marker. If both are enabled, the group marker is prefered if the player has a group. Otherwise the private marker will be added, but never both");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "deleteOldDeathMarker", "enable / disable if old Death Markers should be deleted or must be deleted manually by the player");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "deathMarkerIcon", "Icon of the Death Marker");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "availableIcons", "List of all Icons the Players can choose from when creating a new Marker");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "requireItemToSeeGroupMembers", "Enable is you need to have an item with you to see other group members");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "requireItemToBeSeenByGroupMembers", "Enable is you need to have an item to be seen by the other group members");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "playerMarkerItems", "One of the items is required in the inventory for the 2 options above");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "disableMarkerPlacement", "Disable if players should be able to place any markers. Includes group and private markers.");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "groupMarkerLimit", "Base limit of Group Markers, that can be added (can be expanded per level in the levels.json)");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "tacticalPingLifetimeSeconds", "Time before a Tactical Ping will be deleted automatically");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "tacticalPingMaxConcurrentMarkersPerPlayer", "Amount of tactical Pings each player can place. This can be increased per level in the [Levels.json](?id=6). Trying to place more than the limit will delete the oldest ping");
		RegisterClassVariableComment("LBMarkerSettingsConfig", "offlinePlayer3dMarkerDistance", "Distance the Offline Member Markers should be shown in 3D (numbers smaller than 0 will disable it)");
		RegisterClassComment("LBMuteConfig", "Contains a list of all Muted Players. This will be overwritten while the Server is running !\n\nIf you want to unmute a player or mute a player, use the ingame Admin Menu");
		RegisterClassVariableComment("LBMuteConfig", "mutedPlayers", "List of all Muted Players. Param1 = Players Steamid, Param2 = Unix Timestamp when mute expires, Param3 = Player Name");
		RegisterClassComment("LBPagesConfig", "This config controls the pages on the map menu. Read this guide here fully, before you edit it.");
		RegisterClassVariableComment("LBPagesConfig", "infoPageSettings", "Settings related to the info page");
		RegisterClassVariableComment("LBInfoPageSettings", "enabled", "Enable / Disable the Button in the Map Panel");
		RegisterClassVariableComment("LBInfoPageSettings", "priority", "Priority for the button. Higher priorities will place it further to the left. Priorities of other buttons: (Info: 500, Group: 450, Markers: 400, Settings: 350, Achievements: 120, Item Restrictions: 100) Make sure to have a higher or lower priority setup here if you want to position it brefore or behind a button");
		RegisterClassVariableComment("LBInfoPageSettings", "buttonText", "Name of the button on the Map Panel");
		RegisterClassVariableComment("LBInfoPageSettings", "showSurvivorCount", "Show the Amount of online Players on the Info Panel of the Map");
		RegisterClassVariableComment("LBInfoPageSettings", "showCursorCoordinates", "Show the current cursor Coordinates on the Info Panel of the Map");
		RegisterClassVariableComment("LBInfoPageSettings", "showPlayerPositionCoordinates", "Show the current Player Position on the Info Panel of the Map");
		RegisterClassVariableComment("LBInfoPageSettings", "showIngameTime", "Show the current Ingame Time on the Info Panel of the Map");
		RegisterClassVariableComment("LBInfoPageSettings", "showRealTime", "Show the current Real Time on the Info Panel of the Map (Time set as system Time on the server)");
		RegisterClassVariableComment("LBInfoPageSettings", "enableModCreatorMention", "disable if the small message with my Name should be hidden on the Info panel");
		RegisterClassVariableComment("LBInfoPageSettings", "buttonConfig", "List of all Buttons shown on the Info Panel:");
		RegisterClassVariableComment("LBButtonConfig", "buttonName", "Display Name of the Button (Text on the Button)");
		RegisterClassVariableComment("LBButtonConfig", "subtext", "Short descriptive Text under the button");
		RegisterClassVariableComment("LBButtonConfig", "hoverTooltip", "Tooltip displayed when hovering over the button");
		RegisterClassVariableComment("LBButtonConfig", "link", "URL to the Website, that should be opened if the button is clicked");
		RegisterClassVariableComment("LBPagesConfig", "groupPageSettings", "Settings related to the groups create and manage page");
		RegisterClassVariableComment("LBPageSettings", "enabled", "Enable / Disable the Button in the Map Panel");
		RegisterClassVariableComment("LBPageSettings", "priority", "Priority for the button. Higher priorities will place it further to the left. Priorities of other buttons: (Info: 500, Group: 450, Markers: 400, Settings: 350, Achievements: 120, Item Restrictions: 100) Make sure to have a higher or lower priority setup here if you want to position it brefore or behind a button");
		RegisterClassVariableComment("LBPageSettings", "buttonText", "Name of the button on the Map Panel");
		RegisterClassVariableComment("LBPagesConfig", "markersPageSettings", "Settings related to the markers page");
		RegisterClassVariableComment("LBPageSettings", "enabled", "Enable / Disable the Button in the Map Panel");
		RegisterClassVariableComment("LBPageSettings", "priority", "Priority for the button. Higher priorities will place it further to the left. Priorities of other buttons: (Info: 500, Group: 450, Markers: 400, Settings: 350, Achievements: 120, Item Restrictions: 100) Make sure to have a higher or lower priority setup here if you want to position it brefore or behind a button");
		RegisterClassVariableComment("LBPageSettings", "buttonText", "Name of the button on the Map Panel");
		RegisterClassVariableComment("LBPagesConfig", "settingsPageSettings", "Settings for the client settings page");
		RegisterClassVariableComment("LBPageSettings", "enabled", "Enable / Disable the Button in the Map Panel");
		RegisterClassVariableComment("LBPageSettings", "priority", "Priority for the button. Higher priorities will place it further to the left. Priorities of other buttons: (Info: 500, Group: 450, Markers: 400, Settings: 350, Achievements: 120, Item Restrictions: 100) Make sure to have a higher or lower priority setup here if you want to position it brefore or behind a button");
		RegisterClassVariableComment("LBPageSettings", "buttonText", "Name of the button on the Map Panel");
		RegisterClassVariableComment("LBPagesConfig", "achievementsPageSettings", "Settings for the achievements page when the achievements mod is loaded");
		RegisterClassVariableComment("LBPageSettings", "enabled", "Enable / Disable the Button in the Map Panel");
		RegisterClassVariableComment("LBPageSettings", "priority", "Priority for the button. Higher priorities will place it further to the left. Priorities of other buttons: (Info: 500, Group: 450, Markers: 400, Settings: 350, Achievements: 120, Item Restrictions: 100) Make sure to have a higher or lower priority setup here if you want to position it brefore or behind a button");
		RegisterClassVariableComment("LBPageSettings", "buttonText", "Name of the button on the Map Panel");
		RegisterClassVariableComment("LBPagesConfig", "itemRestrictionsPageSettings", "Settings for the item restrictions page when Enhanced Item restrictions is loaded");
		RegisterClassVariableComment("LBPageSettings", "enabled", "Enable / Disable the Button in the Map Panel");
		RegisterClassVariableComment("LBPageSettings", "priority", "Priority for the button. Higher priorities will place it further to the left. Priorities of other buttons: (Info: 500, Group: 450, Markers: 400, Settings: 350, Achievements: 120, Item Restrictions: 100) Make sure to have a higher or lower priority setup here if you want to position it brefore or behind a button");
		RegisterClassVariableComment("LBPageSettings", "buttonText", "Name of the button on the Map Panel");
		RegisterClassVariableComment("LBPagesConfig", "leaderboardPageSettings", "Settings for the leaderboard page when my Leaderboard mod is loaded");
		RegisterClassVariableComment("LBPageSettings", "enabled", "Enable / Disable the Button in the Map Panel");
		RegisterClassVariableComment("LBPageSettings", "priority", "Priority for the button. Higher priorities will place it further to the left. Priorities of other buttons: (Info: 500, Group: 450, Markers: 400, Settings: 350, Achievements: 120, Item Restrictions: 100) Make sure to have a higher or lower priority setup here if you want to position it brefore or behind a button");
		RegisterClassVariableComment("LBPageSettings", "buttonText", "Name of the button on the Map Panel");
		RegisterClassVariableComment("LBPagesConfig", "customPages", "Custom pages you can add for any information you want to display like ingame guides, rules or basically anything else");
		RegisterClassVariableComment("LBCustomPageSettings", "enabled", "Enable / Disable the Button in the Map Panel");
		RegisterClassVariableComment("LBCustomPageSettings", "priority", "Priority for the button. Higher priorities will place it further to the left. Priorities of other buttons: (Info: 500, Group: 450, Markers: 400, Settings: 350, Achievements: 120, Item Restrictions: 100) Make sure to have a higher or lower priority setup here if you want to position it brefore or behind a button");
		RegisterClassVariableComment("LBCustomPageSettings", "buttonText", "Name of the button on the Map Panel");
		RegisterClassVariableComment("LBCustomPageSettings", "fullSize", "Set the panel to full size to fill the whole screen when opened. When disabled, it will only take up the left panel on the map. Useful if you don't want to show a lot of information on this page and don't want it to take up the whole screen");
		RegisterClassVariableComment("LBCustomPageSettings", "lines", "Lines for the page. Read the [How to format lines](/faq/?id=151) guide. Each new entry in this list is a new line. Line breaks are added automatically, but it's highly recommended to not rely on them, because DayZ has some inconsistencies causing lines to sometimes not show correctly.");
		RegisterClassComment("LBColorManager", "");
		RegisterClassComment("LBGroupManager", "This file is a Group file with all the info realted to a single group on the server.\n\nDo not edit this file while the server is running! All information will be overwritten.\n\nIt's also recommended to use the ingame admin menu to make any changes to groups or delete them instead of manipulating the Json file!");
		RegisterClassVariableComment("LBGroupManager", "name", "Long name of the Group");
		RegisterClassVariableComment("LBGroupManager", "shortname", "Short name (Tag) also used as the filename of the group");
		RegisterClassVariableComment("LBGroupManager", "level", "Current level of the Group");
		RegisterClassVariableComment("LBGroupManager", "lastActivity", "Unix Timestamp when a player was last active in the group (used to delete inactive groups)");
		RegisterClassVariableComment("LBGroupManager", "creationDate", "Unix Timestamp when the group was created");
		RegisterClassVariableComment("LBGroupManager", "showTagInChat", "Group Leaders can toggle if their group tag should be shown in tag if not set to force show them in the Chatconfig.json. This is saved here");
		RegisterClassVariableComment("LBGroupManager", "hasCustomChatColor", "Set to 1 to apply the custom tag color defined below. Otherwise it will be the handled by the Chat");
		RegisterClassVariableComment("LBGroupManager", "customChatColorAppliedByPlayer", "will be 1 if the tag was changed by a player to prevent people from joining groups to change their tag colors");
		RegisterClassVariableComment("LBGroupManager", "chatColorR", "Custom Chat Tag Red color");
		RegisterClassVariableComment("LBGroupManager", "chatColorG", "Custom Chat Tag Green color");
		RegisterClassVariableComment("LBGroupManager", "chatColorB", "Custom Chat Tag Blue color");
		RegisterClassVariableComment("LBGroupManager", "members", "List of all Members in this group");
		RegisterClassVariableComment("LBGroupMember", "type", "Type of the Marker. 0 = Static Marker (persistent), 1 = Dynamic Marker (deleted after server restart), 2 = Ping Marker, 3 = Group Marker, 4 = Group Player Marker, 5 = Private Marker");
		RegisterClassVariableComment("LBGroupMember", "uid", "Unique ID of the Marker. This should be unique, otherwise it will only be displayed once in the Marker list. If you have a lot of the same markers like extracts, you can give it the same UID for all Markers, so you only have it once in the Marker list. Otherwise do not use the same UID for multiple markers");
		RegisterClassVariableComment("LBGroupMember", "name", "Name displayed on the map");
		RegisterClassVariableComment("LBGroupMember", "icon", "Icon Path for this marker");
		RegisterClassVariableComment("LBGroupMember", "position", "Position of the Marker");
		RegisterClassVariableComment("LBGroupMember", "currentSubgroup", "Only relevant for Group Player Markers (Type 4) to keep track of which subgroup the player joined. Also used for pings to check if they should be displayed");
		RegisterClassVariableComment("LBGroupMember", "colorA", "Alpha (Transparency) Color of this marker and the icon. 255 for fully opaque and 0 for fully transparent");
		RegisterClassVariableComment("LBGroupMember", "colorR", "Red Color");
		RegisterClassVariableComment("LBGroupMember", "colorG", "Green Color");
		RegisterClassVariableComment("LBGroupMember", "colorB", "Blue Color");
		RegisterClassVariableComment("LBGroupMember", "creatorSteamID", "Steamid of the user created this marker");
		RegisterClassVariableComment("LBGroupMember", "circleRadius", "If set to something greater than 0, this marker will have a radius marked around it");
		RegisterClassVariableComment("LBGroupMember", "circleColorA", "Alpha Color of the circle");
		RegisterClassVariableComment("LBGroupMember", "circleColorR", "Red Color of the circle");
		RegisterClassVariableComment("LBGroupMember", "circleColorG", "Green Color of the circle");
		RegisterClassVariableComment("LBGroupMember", "circleColorB", "Blue Color of the circle");
		RegisterClassVariableComment("LBGroupMember", "circleStriked", "Set to 1, the circle will have lines to fill the circle. When set to 0, only the border of the circle will be shown");
		RegisterClassVariableComment("LBGroupMember", "circleLayer", "Multiple Circles sharing a single layer will intersect with eachother instead of overlap");
		RegisterClassVariableComment("LBGroupMember", "showAllPlayerNametags", "When set to 1, playernames above the players will be shown within the circle radius. If you only want to see the playernames and don't want to show the radius, set the Alpha color to 0");
		RegisterClassVariableComment("LBGroupMember", "steamid", "Steamid of the Player in the Group");
		RegisterClassVariableComment("LBGroupMember", "permissionGroup", "ID of the Permission group found in the Permissions.json");
		RegisterClassVariableComment("LBGroupMember", "online", "will be updated by the server if the player is currently online");
		RegisterClassVariableComment("LBGroupMember", "health", "HP of the Player (0 - 100.0)");
		RegisterClassVariableComment("LBGroupMember", "tempMember", "Set to 1 if the player is only temporarily part of the group (joined as secondary group)");
		RegisterClassVariableComment("LBGroupMember", "lastSubgroup", "Save the last subgroup the player was in when he left the server and he is moved to an offline subgroup");
		RegisterClassVariableComment("LBGroupMember", "moveToLastSubgroup", "If the player should be moved back to a different subgroup when he joins the server");
		RegisterClassVariableComment("LBGroupManager", "markers", "List of all placed group Markers. This does not include pings. They are not persistent and not saved here.");
		RegisterClassVariableComment("LBMarker", "type", "Type of the Marker. 0 = Static Marker (persistent), 1 = Dynamic Marker (deleted after server restart), 2 = Ping Marker, 3 = Group Marker, 4 = Group Player Marker, 5 = Private Marker");
		RegisterClassVariableComment("LBMarker", "uid", "Unique ID of the Marker. This should be unique, otherwise it will only be displayed once in the Marker list. If you have a lot of the same markers like extracts, you can give it the same UID for all Markers, so you only have it once in the Marker list. Otherwise do not use the same UID for multiple markers");
		RegisterClassVariableComment("LBMarker", "name", "Name displayed on the map");
		RegisterClassVariableComment("LBMarker", "icon", "Icon Path for this marker");
		RegisterClassVariableComment("LBMarker", "position", "Position of the Marker");
		RegisterClassVariableComment("LBMarker", "currentSubgroup", "Only relevant for Group Player Markers (Type 4) to keep track of which subgroup the player joined. Also used for pings to check if they should be displayed");
		RegisterClassVariableComment("LBMarker", "colorA", "Alpha (Transparency) Color of this marker and the icon. 255 for fully opaque and 0 for fully transparent");
		RegisterClassVariableComment("LBMarker", "colorR", "Red Color");
		RegisterClassVariableComment("LBMarker", "colorG", "Green Color");
		RegisterClassVariableComment("LBMarker", "colorB", "Blue Color");
		RegisterClassVariableComment("LBMarker", "creatorSteamID", "Steamid of the user created this marker");
		RegisterClassVariableComment("LBMarker", "circleRadius", "If set to something greater than 0, this marker will have a radius marked around it");
		RegisterClassVariableComment("LBMarker", "circleColorA", "Alpha Color of the circle");
		RegisterClassVariableComment("LBMarker", "circleColorR", "Red Color of the circle");
		RegisterClassVariableComment("LBMarker", "circleColorG", "Green Color of the circle");
		RegisterClassVariableComment("LBMarker", "circleColorB", "Blue Color of the circle");
		RegisterClassVariableComment("LBMarker", "circleStriked", "Set to 1, the circle will have lines to fill the circle. When set to 0, only the border of the circle will be shown");
		RegisterClassVariableComment("LBMarker", "circleLayer", "Multiple Circles sharing a single layer will intersect with eachother instead of overlap");
		RegisterClassVariableComment("LBMarker", "showAllPlayerNametags", "When set to 1, playernames above the players will be shown within the circle radius. If you only want to see the playernames and don't want to show the radius, set the Alpha color to 0");
		RegisterClassComment("LBGroupSettingsConfig", "This config handles all group related settings except for levels. They are setup in the Levels.json file.");
		RegisterClassVariableComment("LBGroupSettingsConfig", "inactiveGroupLifetimeDays", "Time after a group will be deleted when no member was active for x Days");
		RegisterClassVariableComment("LBGroupSettingsConfig", "inviteCooldownSeconds", "Time a player needs to wait to invite the same player again to prevent spam");
		RegisterClassVariableComment("LBGroupSettingsConfig", "inviteActionEnabled", "When enabled, players can only use the ingame action to invite people and cannot see the list of players to invite them on the map menu. If you don't see the list of online players on the Group manage page, but you want to have it, disable this option");
		RegisterClassVariableComment("LBGroupSettingsConfig", "inviteActionShowName", "Show the name of the player you invite in the action text");
		RegisterClassVariableComment("LBGroupSettingsConfig", "preventFriendlyFire", "Set to 1 to disable players taking damage from players, which are in the same group as them. That only prevents the player from dying from direct hits like bullets fired by the other player or melee hits. Things like clothing will still be damaged");
		RegisterClassVariableComment("LBGroupSettingsConfig", "preventFriendlyFireOnlyInSameSubgroup", "Set to 1 to only prevent friendly fire when they are in the same subgroup (`enableSubGroups` must be enabled for that). Otherwise players will still take damage even though they are in the same group");
		RegisterClassVariableComment("LBGroupSettingsConfig", "groupManagePageObfuscatePlayernames", "enable / disable player Names being displayed in the Player list. If disabled the Names will be shown as usual. If enabled, the names will just be random numbers, which change every restart");
		RegisterClassVariableComment("LBGroupSettingsConfig", "enablePlayerList", "enable / disable the Player List in the top left corner");
		RegisterClassVariableComment("LBGroupSettingsConfig", "enablePlayerListDistance", "enable / disable if the Distance to the other Players should be displayed in the Player List");
		RegisterClassVariableComment("LBGroupSettingsConfig", "allowJoinSecondGroupTemporarily", "Enable secondary groups to not have to leave the main group to temporarily join another group");
		RegisterClassVariableComment("LBGroupSettingsConfig", "removeTemporaryMemberOnServerStart", "Enable if players should be removed from the temporary group on restart. Otherwise the player needs to leave the group or you enable `removeTemporaryMemberOnPlayerLeave`");
		RegisterClassVariableComment("LBGroupSettingsConfig", "removeTemporaryMemberOnPlayerLeave", "Enable if players should be removed from the temporary group when he leaves the server / logs out or server restart. Otherwise players need to actively leave the temporary group");
		RegisterClassVariableComment("LBGroupSettingsConfig", "enableSubGroups", "enable / disable subgroups / firegroups to split larger groups into smaller groups. This should make it harder for larger groups to run around as on big squad and wipe out every small group");
		RegisterClassVariableComment("LBGroupSettingsConfig", "enableSubGroupSharedPlayerMapMarker", "If enabled, the players can still see eachother even if not in the same subgroup, which makes the subgroups pointless");
		RegisterClassVariableComment("LBGroupSettingsConfig", "enableSubGroupSharedPingMapMarker", "Enable if the Ping Markers should be shared in the subgroups");
		RegisterClassVariableComment("LBGroupSettingsConfig", "showLevelUpgradeBenefits", "Show new benefits when upgrading the Group (Player limit, marker limit, plotpole limit, subgroup limits)");
		RegisterClassVariableComment("LBGroupSettingsConfig", "subGroupNames", "Names of the Subgroups. Make sure you have enough names for the amount of subgroups for the highest level (see levels.json)");
		RegisterClassVariableComment("LBGroupSettingsConfig", "blacklistedGroupNames", "List of group names, which are not allowed on your server. the names are not case sensitive, but have to match, so adding another character at the start or end will no longer match. This is working for group names and group tags. Player will get an error message telling them the name is already used when trying to use a blacklisted name");
		RegisterClassComment("LBLayoutConfig", "");
		RegisterClassVariableComment("LBLayoutConfig", "playerlistLayoutIndex", "");
		RegisterClassVariableComment("LBLayoutConfig", "gpsSizeIndex", "");
		RegisterClassVariableComment("LBLayoutConfig", "playerMarkerPosIndex", "");
		RegisterClassVariableComment("LBLayoutConfig", "playerMarkerStyleIndex", "");
		RegisterClassVariableComment("LBLayoutConfig", "gpsZoom", "");
		RegisterClassVariableComment("LBLayoutConfig", "streamerModeEnabled", "");
		RegisterClassComment("LBMarkerVisibilityManager", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "entries", "");
		RegisterClassVariableComment("LBMarkerVisibilityEntry", "uid", "");
		RegisterClassVariableComment("LBMarkerVisibilityEntry", "displaystate", "0 3D+2D // 1 2D // 2 None");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "globalentries", "");
		RegisterClassVariableComment("LBGlobalVisibilityEntry", "type", "");
		RegisterClassVariableComment("LBGlobalVisibilityEntry", "displaystate", "0 3D+2D // 1 2D // 2 None");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "hiddenChannels", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "globalVisiblityState", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "pingMarkerIcon", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "playerMarkerIcon", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "compassEnabled", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "playerlistEnabled", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "showNoBuildZones", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "disableShowClantextures", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "gpsEnabled", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "centerMapOnPlayer", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "pingSize", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "playerSize", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "chatSize", "");
		RegisterClassVariableComment("LBMarkerVisibilityManager", "chatBorderVisibility", "");
		RegisterClassComment("LBPrivateMarkerManager", "");
		RegisterClassComment("LBSafezoneMarkers", "This file contains the config for Safezone Markers. They are only markers and do not add any safezone functionality.\n\nThis config also doesn't automatically take the safezones from other mods. They need to be marked by setting the `showAllPlayerNametags` for static markers to 1 or check the box ingame to make it a safezone marker.\n\nThe zones themselves are static markers with the `showAllPlayerNametags` parameter set to 1. They need a radius set too. The color of the radius can be invisible (circleColorA set to 0), if you don't want to show the circle on the map, but still want the nametags to be visible");
		RegisterClassVariableComment("LBSafezoneMarkers", "enablePlayerMarkers", "Enable / disable the whole feature");
		RegisterClassVariableComment("LBSafezoneMarkers", "showMarkersEverywhere", "Enable if markers should be visible everywhere on the whole map ignoring the zones of the static markers");
		RegisterClassVariableComment("LBSafezoneMarkers", "checkLineOfSight", "Check the line of sight from the player to the other players head");
		RegisterClassVariableComment("LBSafezoneMarkers", "obfuscatePlayerNames", "Show the obfuscated version of the Playernames instead of the real names. Will behave exactly the same like the obfuscation of player names on the online players list for the group invites. The IDs of the players will also be printed in the LBmaster log when they login so you can find out who the person was");
		RegisterClassVariableComment("LBSafezoneMarkers", "showOwnPlayerTag", "Enable if the tag of the own player should be displayed or hidden");
		RegisterClassVariableComment("LBSafezoneMarkers", "maxPlayerDistance", "Maximum distance the nametags will be shown. Cannot exceed the network far bubble (~1000m by default)");
		RegisterClassVariableComment("LBSafezoneMarkers", "safezoneMarkers", "List of all prefixes. You should always have one with no permissions, otherwise normal players will not have a prefix!");
		RegisterClassVariableComment("LBSafezoneMarkerEntry", "prefix", "Prefix infront of the playername. Will not be displayed when playername obfuscation is enabled");
		RegisterClassVariableComment("LBSafezoneMarkerEntry", "color", "Color of the tag");
		RegisterClassVariableComment("LBSafezoneMarkerEntry", "permission", "Permission required to have this prefix and color applied. Grant all permissions is ignored. Make sure to have exactly 1 entry with an empty permission");
		RegisterClassVariableComment("LBSafezoneMarkerEntry", "ignoreNameObfuscationSetting", "When enabled and playername obfuscation is enabled in the config, players with this tag will still have their plain name displayed");
		RegisterClassComment("LBStaticMarkerManager", "This config contains all static markers on the server. It is possible to add the static markers here, especially if you need a little more control over the markers, than you have with the ingame admin menu\n\nI still highly recomment using the ingame Admin menu to add static markers on your server. It's a lot easier for the initial setup.\n\nMake sure you are added to the Admins.json in your Config/Common/Admins.json file and have admin mode enabled. Then just place a marker on the map and change the type to Server Marker (perm) to add a static marker. You can define Name, Icon, Color and Radius ingame, which should be enough for everyone.\n\nMake sure if you do want to edit this file, to do that while the server is offline, otherwise changes are likely to be overwritten by the server.");
		RegisterClassVariableComment("LBServerMarker", "type", "Type of the Marker. 0 = Static Marker (persistent), 1 = Dynamic Marker (deleted after server restart), 2 = Ping Marker, 3 = Group Marker, 4 = Group Player Marker, 5 = Private Marker");
		RegisterClassVariableComment("LBServerMarker", "uid", "Unique ID of the Marker. This should be unique, otherwise it will only be displayed once in the Marker list. If you have a lot of the same markers like extracts, you can give it the same UID for all Markers, so you only have it once in the Marker list. Otherwise do not use the same UID for multiple markers");
		RegisterClassVariableComment("LBServerMarker", "name", "Name displayed on the map");
		RegisterClassVariableComment("LBServerMarker", "icon", "Icon Path for this marker");
		RegisterClassVariableComment("LBServerMarker", "position", "Position of the Marker");
		RegisterClassVariableComment("LBServerMarker", "currentSubgroup", "Only relevant for Group Player Markers (Type 4) to keep track of which subgroup the player joined. Also used for pings to check if they should be displayed");
		RegisterClassVariableComment("LBServerMarker", "colorA", "Alpha (Transparency) Color of this marker and the icon. 255 for fully opaque and 0 for fully transparent");
		RegisterClassVariableComment("LBServerMarker", "colorR", "Red Color");
		RegisterClassVariableComment("LBServerMarker", "colorG", "Green Color");
		RegisterClassVariableComment("LBServerMarker", "colorB", "Blue Color");
		RegisterClassVariableComment("LBServerMarker", "creatorSteamID", "Steamid of the user created this marker");
		RegisterClassVariableComment("LBServerMarker", "circleRadius", "If set to something greater than 0, this marker will have a radius marked around it");
		RegisterClassVariableComment("LBServerMarker", "circleColorA", "Alpha Color of the circle");
		RegisterClassVariableComment("LBServerMarker", "circleColorR", "Red Color of the circle");
		RegisterClassVariableComment("LBServerMarker", "circleColorG", "Green Color of the circle");
		RegisterClassVariableComment("LBServerMarker", "circleColorB", "Blue Color of the circle");
		RegisterClassVariableComment("LBServerMarker", "circleStriked", "Set to 1, the circle will have lines to fill the circle. When set to 0, only the border of the circle will be shown");
		RegisterClassVariableComment("LBServerMarker", "circleLayer", "Multiple Circles sharing a single layer will intersect with eachother instead of overlap");
		RegisterClassVariableComment("LBServerMarker", "showAllPlayerNametags", "When set to 1, playernames above the players will be shown within the circle radius. If you only want to see the playernames and don't want to show the radius, set the Alpha color to 0");
		RegisterClassVariableComment("LBServerMarker", "toSurface", "Set to 1 to automatically set the marker to ground pos at the x and z position");
		RegisterClassVariableComment("LBServerMarker", "display3d", "Enable if the marker should be shown in 3D");
		RegisterClassVariableComment("LBServerMarker", "displayMap", "Enable if the marker should be shown on the Map");
		RegisterClassVariableComment("LBServerMarker", "displayGPS", "Enable if the marker should be shown on the GPS");
		RegisterClassComment("LBTerritoryConfig", "This is the Main Config with all Plotpole Settings:\n\nCheck the [How do I install the Plotpole DLC ?](/faq/?id=103) on how to install the Plotpole DLC\n\nIf you have any issues setting it up, refer to the [My Items in the Territories are despawning](/faq/?id=104) and [How do I properly setup the Plotpole variables](/faq/?id=106) FAQ entries");
		RegisterClassVariableComment("LBTerritoryConfig", "enablePlotpoleExtension", "Must be set to 1. Otherwise everything is disabled !");
		RegisterClassVariableComment("LBTerritoryConfig", "enabledDebugLifetimePrints", "Enable if all objects, which are refreshed by the flag should be printed to the log to find any missing items and troubleshoot");
		RegisterClassVariableComment("LBTerritoryConfig", "syncPlotpolesToCFCloud", "Show Plotpoles on the CF Cloud interactive Map");
		RegisterClassVariableComment("LBTerritoryConfig", "doObjectLifetimeReset", "Reset the Lifetime of objects within the Plotpole Radius. When disabled, the Flag will not reset the lifetime of the objects placed and they might despawn");
		RegisterClassVariableComment("LBTerritoryConfig", "flagLifetimeRefreshTime", "analog to the `FlagRefreshFrequency` from the globals.xml. The globals.xml value will be ignored. This is the interval in seconds between two lifetime resets. All Objects, which should not despawn must have a lifetime higher than this value");
		RegisterClassVariableComment("LBTerritoryConfig", "flagUptimeDuration", "analog to the `FlagRefreshMaxDuration` from the globals.xml. The globals.xml value will be ignored. This is how long the Flag will take from 100% up to completely lowered. When the Flag reaches the lowered state, it will once more refresh the lifetime of the objects near it and then the lifetime of the objects remain until they despawn.");
		RegisterClassVariableComment("LBTerritoryConfig", "preventUnauthorizedDeploying", "Set to 1 to prevent people from deploying objects in enemy territories. This will not prevent people from dropping items like barrels !");
		RegisterClassVariableComment("LBTerritoryConfig", "deployInOthersTerritoryExceptions", "List of items, which can still be deployed in enemy territories like C4 or Traps");
		RegisterClassVariableComment("LBTerritoryConfig", "forceDeployingInTerritory", "Set to 1 to force all players to build inside a territory. If set to 0, players can build everywhere, but they are not protected by the Flag");
		RegisterClassVariableComment("LBTerritoryConfig", "forceExceptions", "Exceptions to this rule. Add things like Campfires or similar things to allow people to use them in the wild");
		RegisterClassVariableComment("LBTerritoryConfig", "preventUnauthorizedBuilding", "Set to 1 to disable building basebuilding parts in enemy territories");
		RegisterClassVariableComment("LBTerritoryConfig", "preventUnauthorizedDismantling", "Set to 1 to disable dismantling basebuilding parts in enemy territories");
		RegisterClassVariableComment("LBTerritoryConfig", "preventUnauthorizedDestroying", "Set to 1 to disable destroying of basebuilding parts in enemy territories (DayZ changed the way basebuilding objects are destroyed !)");
		RegisterClassVariableComment("LBTerritoryConfig", "lowerFlagWhenGroupDeleted", "When a group owning the flag is deleted, the flag will be lowered to 0% and no longer refreshes items. Keep in mind: Groups are deleted when the last player in the group left. When disabled, the flag will stay up and refresh all items around potentially leaving abondend bases active instead of letting them decay");
		RegisterClassVariableComment("LBTerritoryConfig", "instantBuildPlotpole", "Instantly build the flagpole when the kit is placed. The Flag does not yield any ressources when destroyed");
		RegisterClassVariableComment("LBTerritoryConfig", "instantDestroyPlotpole", "When any part of the Flagpole is destroyed, the whole flag will be deleted");
		RegisterClassVariableComment("LBTerritoryConfig", "returnFlagpoleKitOnInstantDestroy", "Enable if the Plotpole Kit should be droppen on the ground when the flag is destroyed with `instantDestroyPlotpole` enabled");
		RegisterClassVariableComment("LBTerritoryConfig", "allowDestroyWithFlagAttached", "Enable if the plotpole can be destroyed while the Flag is still attached. When disabled, players can also not cut the flag with a knife to remove the Flag from the Pole");
		RegisterClassVariableComment("LBTerritoryConfig", "maxDistanceToDismantleFlag", "Change the max distance a player can be away from the base of the Flag to destroy it to prevent people from destroying it by only seeing the top of the flag through a house/base roof. Calculated from the player feet to the base of the Flagpole");
		RegisterClassVariableComment("LBTerritoryConfig", "autoAttachFlag", "Attach a random Flag when instant build is enabled and choose a Flag from the list below");
		RegisterClassVariableComment("LBTerritoryConfig", "autoRaiseFlag", "Raise the Flag to 100% when enabled and instant build is enabled");
		RegisterClassVariableComment("LBTerritoryConfig", "autoFlagAttachedItemnames", "List of Flags, that can be attached when autoAttachFlag is enabled. A random itemname will be choosen from the list");
		RegisterClassVariableComment("LBTerritoryConfig", "displayPlotpolesOnMap", "Create a Marker in the Group when the Flag is placed down (this is not public and can be removed)");
		RegisterClassVariableComment("LBTerritoryConfig", "allowOthersPlotpoleDestroy", "Set to 1 to allow players not owning the Flag to destroy it (destroying a flag requires the flag to be lowered !)");
		RegisterClassVariableComment("LBTerritoryConfig", "maxDistanceToLowerFlag", "Similar to the `maxDistanceToDismantleFlag`, but for lowering the flag. Calculated from the player feet to the base of the Flagpole");
		RegisterClassVariableComment("LBTerritoryConfig", "allowOthersPlotpoleLowerFlag", "Set to 1 to allow players not owning the Flag to lower it and stop the lifetime reset of the Basebuilding items");
		RegisterClassVariableComment("LBTerritoryConfig", "allowOthersPlotpoleRaiseFlag", "Set to 1 to allow players not owning the Flag to raise it");
		RegisterClassVariableComment("LBTerritoryConfig", "allowBuildInUnclaimedTeritorry", "Set to 1 to allow anybody to build unprotected basebuilding items e.g. The Flag is despawned or the Group owning it was deleted");
		RegisterClassVariableComment("LBTerritoryConfig", "allowDismantleInUnclaimedTeritorry", "Set to 1 to allow anybody to dismantle unprotected basebuilding items e.g. The Flag is despawned or the Group owning it was deleted");
		RegisterClassVariableComment("LBTerritoryConfig", "allowDestroyInUnclaimedTeritorry", "Set to 1 to allow anybody to destroy unprotected basebuilding items e.g. The Flag is despawned or the Group owning it was deleted");
		RegisterClassVariableComment("LBTerritoryConfig", "teleportPlayerOutInEnemyTerritory", "Set to 1 to teleport players out to the edge of the territory when they login in enemy territory. Unclaimed territories are ignored");
		RegisterClassVariableComment("LBTerritoryConfig", "treatFullyLoweredPlotpolesLikeUnclaimedPlotpoles", "when enabled and a flag is at 0%, it will apply the permissions for unclaimed flags for anyone not authorized for the flag instead of the permissions for unauthorized players");
		RegisterClassVariableComment("LBTerritoryConfig", "plotpoleRadius", "Radius of the Plotpole (Shape of the Radius is a Cylinder, not a Sphere !)");
		RegisterClassVariableComment("LBTerritoryConfig", "plotpoleHeightUp", "Height up of the Plotpole radius from the center of the plotpole");
		RegisterClassVariableComment("LBTerritoryConfig", "plotpoleHeightDown", "Height down from the Plotpole center");
		RegisterClassVariableComment("LBTerritoryConfig", "plotpoleRadius_InsidePvEZone", "Overwrites the radius of the flag when inside a PvE Zone (PVEZ mod supported)");
		RegisterClassVariableComment("LBTerritoryConfig", "plotpoleHeightUp_InsidePvEZone", "Overwrites the radius of the flag when inside a PvE Zone (PVEZ mod supported)");
		RegisterClassVariableComment("LBTerritoryConfig", "plotpoleHeightDown_InsidePvEZone", "Overwrites the radius of the flag when inside a PvE Zone (PVEZ mod supported)");
		RegisterClassVariableComment("LBTerritoryConfig", "plotpoleDistanceMinHostile", "Minimum distance between Plotpoles when owned by different Groups. Also checked when trying to claim a flag");
		RegisterClassVariableComment("LBTerritoryConfig", "plotpoleDistanceMinFriendly", "Minimum distance between Plotpoles when owned by the same Group. Also checked when trying to claim a flag");
		RegisterClassVariableComment("LBTerritoryConfig", "defaultPlotpoleCountPerGroup", "Plotpole Limit for each Group (can be upgraded via the Level.json)");
		RegisterClassVariableComment("LBTerritoryConfig", "territoryInfoTitle", "Title of the territory entered / left messages");
		RegisterClassVariableComment("LBTerritoryConfig", "showEnemyTerritoryEnteredMessage", "Show a message when the player enteres an enemy territory");
		RegisterClassVariableComment("LBTerritoryConfig", "showEnemyTerritoryLeftMessage", "Show a message when the player leaves an enemy territory");
		RegisterClassVariableComment("LBTerritoryConfig", "enemyTerritoryEnteredMessage", "The message displayed when entering enemy territory (%groupname% and %grouptag% can be used as placeholder)");
		RegisterClassVariableComment("LBTerritoryConfig", "enemyTerritoryLeftMessage", "The message displayed when leaving enemy territory (%groupname% and %grouptag% can be used as placeholder)");
		RegisterClassVariableComment("LBTerritoryConfig", "unclaimedTerritoryEnteredMessage", "The message displayed when entering territory, which is unclaimed");
		RegisterClassVariableComment("LBTerritoryConfig", "unclaimedTerritoryLeftMessage", "The message displayed when leaving territory, which is unclaimed");
		RegisterClassVariableComment("LBTerritoryConfig", "showOwnTerritoryEnteredMessage", "Show a message when the player enteres an owned territory by the player");
		RegisterClassVariableComment("LBTerritoryConfig", "showOwnTerritoryLeftMessage", "Show a message when the player leaves an owned territory by the player");
		RegisterClassVariableComment("LBTerritoryConfig", "ownTerritoryEnteredMessage", "The message displayed when entering owned territory (%groupname% and %grouptag% can be used as placeholder)");
		RegisterClassVariableComment("LBTerritoryConfig", "ownTerritoryLeftMessage", "The message displayed when leaving owned territory (%groupname% and %grouptag% can be used as placeholder)");
		RegisterClassComment("LBGroupFilesList", "Used for Linux servers as a workaround, because DayZ is currently broken on Linux and cannot load the file list of a folder causing groups to not load when the server restarts, because it cannot read the content of the LBmaster/Data/LBGroup/Groups folder thinking no groups exist. https://feedback.bistudio.com/T182004\nWindows servers will ignore the content of the file and still read the file list of the folder as usual.");
		RegisterClassVariableComment("LBGroupFilesList", "groups", "List of the groups, which are known to exist in the LBGroup folder");
		RegisterClassComment("LBGroupTimeoutList", "Config that contains all current timeouts\n\nDo not edit this file directly! The server will overwrite any changes, so use the ingame admin menu to reset timeouts or edit the timeouts config");
		RegisterClassVariableComment("LBGroupTimeoutList", "players", "List of all current player timeouts");
		RegisterClassVariableComment("LBGroupTimeoutEntry", "steamid", "Steamid of the Player");
		RegisterClassVariableComment("LBGroupTimeoutEntry", "lastGroup", "The last group the player was in to track if he joins the same group or a different group and to apply the according timeout set above");
		RegisterClassVariableComment("LBGroupTimeoutEntry", "timeoutStartTimestamp", "Unix timestamp when the Player jast **joined** the `lastGroup` so players which have been in a group for a long time and want to change the group will not be punished, but players wanting to swap groups all the time will have the timeout");
		RegisterClassComment("LBAutomarkerConfig", "This config is used to automatically add markers to the map, whithout having to do any scripting work\nThis can be used for marking vanilla Helicrahes or different things. An example on how you would mark helicrashes is included in the default config\nThis can also be used to track players in vehicles in a car race\nBe aware, that all markers will be STATIC_DYNAMIC markers. So they will be visible for all players and will be deleted when the object they belog to is deleted or when the server restarts\nNew markers are created when the server starts and also when new objects are created. For example a helicrash spawns, then the marker will be added. When it despawns, then the marker will be deleted again\nThis can also be used to mark things like Traders on the map");
		RegisterClassVariableComment("LBAutomarkerConfig", "enabled", "Enable / disable the whole system");
		RegisterClassVariableComment("LBAutomarkerConfig", "automaticMarkers", "List of markers you want to have added to the map automatically");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "itemnames", "List of itemnames, which should automatically have a marker attached");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "markerIcon", "Icon path of the marker. You can use custom files as long as the path is correct and they exist or use one from the list in the Mainconfig.json");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "markerName", "Display Name of the Marker. This can have several Placeholders: `{displayName}` will be replaced with the Display Name of the Item the marker is attached to. `{rootDisplayName}` will look for the root owner of the item (for example a player, who has the item in his inventory) or it will be the same as `{displayName}` if there is no item higher up the hierarchy. You can also let it execute a whole script function, which must return a string. This function must exist in the script Class of this entity ! Otherwise it will not work and could lead to crashes ! `{TheFunctionName()}` would call a function `string TheFunctionName() {return \"My cool string\";}`. This function must not be static or private and must exist in the Class of the entity where the marker is added to");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "yOffset", "Additional height offset from the origin of the Item. Some items have a very low center. You can add an additional Y-Offset here to place the marker a bit higher (only relevant if you use 3D Markers)");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "updateInvervalSeconds", "If set to a value greater than 0, the position of all markers of this category will be updated each x seconds. By default markers are not updated after they were initially placed. If you want them to update, then you need to define an interval here. This would be used for something like a car race. Heli Crashes do not need to be updated, because they will stay at the same position the whole time");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "display3D", "Enable / Disable 3D Markers for this Auto Marker");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "displayMap", "Enable / Disable if the marker should be shown on the map");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "displayGPS", "Enable / Disable if the marker should be shown on the GPS");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "markerColorFunction", "Similar to the placeholders in the `markerName`, you can define a custom function, which should be called to get the color of the marker. If left blank (`\"" + "\"`), then `markerColor` is used as a static color, which should be enough for most use cases. If you want the color to change, you first need to have an updateInvervalSeconds set. Otherwise it will never check if the color should be updated. And you also need to put a function name in here, which exists in the Class of the entity the marker is added to. **Make sure to not have () at the end ! Only use the function name !** The function must return an ARGB int value. so for example `int GetMyColor() {return ARGB(255,255,255,255);}` would return a white color all the time. You then need to have `\"GetMyColor\"` as the value of this parameter");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "markerColor", "Default color of the Marker and Icon when no `markerColorFunction` is set");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "markerRadiusFunction", "Same as the `markerColorFunction`, but now it must return a float");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "radius", "default radius of the marker");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "radiusColorFunction", "Same as the `markerColorFunction`, but now for the color of the radius");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "radiusColor", "Color of the outer edge of the radius");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "strikedRadius", "Enable / disable the striked style of the inner part of radius");
		RegisterClassVariableComment("LBAutoMarkerConfigEntry", "showOnlyInsideStaticMarkerRadius", "If enabled, markers will only be added to items which are inside static markers with a radius (markers added to the staticmarkers.json). This can be useful to mark all Traders or ATMs, but only the ones in the safezones and maybe not the ones hidden on the map");
		RegisterClassComment("LBClanClothingConfig", "This file contains the config for the Clan Clothing. You can have one entry for each item, which will automatically be retextured when worn by a player\nYou can already do a lot with this feature, but if you want to have more than one texture per item or more control over who can use which retexture, you can buy the Skin System mod from my website");
		RegisterClassVariableComment("LBClanClothingConfig", "active", "enable / disable Clan clothing extension");
		RegisterClassVariableComment("LBClanClothingConfig", "entries", "List of all ClanClothing entries");
		RegisterClassVariableComment("LBClanClothingConfigEntry", "clanTags", "List of all Clans, which this config should apply to (clans can be in multiple configs)");
		RegisterClassVariableComment("LBClanClothingConfigEntry", "steamids", "List of individual Players, which this config should apply to (players can be in multiple configs)");
		RegisterClassVariableComment("LBClanClothingConfigEntry", "itemNames", "List of the Itemnames, which should be retextured");
		RegisterClassVariableComment("LBClanClothingConfigEntry", "fileNames", "List of the Paths to the hiddenSelectionTextures of the item (blank is the default texture)\n\n\n\n`itemNames` and `fileNames` must be of the same length !\n\nThe first entry for an Item will correspond to the first hiddenSelection of this item.\n\nAdding an Item to this list will not create a new Item ! It will only change the texture of this item\n\n\n__Example:__\n\nRetexture of Hoodie_Black (defined in DZ/characters/tops/config.cpp):\n\n__Step 1:__\n\nCheck how many hidden selections the item has\n\nHidden Selections for the Hoddie and almost all clothing items: `hiddenSelections[] = {\"camoGround\",\"camoMale\",\"camoFemale\"};` (3)\n\n__Step 2:__\n\nFind the path of the texture you want to add to the config. Something like `MyClothingMod/textures/hoodie/xyz/texture_co.paa`\n\n__Step 3:__\n\nEdit the config. You can add a new Entry for a Clan like this:\n\n```json\n{\n\"clanTags\": [\"XYZ\"],\n\"steamids\": [],\n\"itemNames\": [\n\"Hoodie_Black\",\n\"Hoodie_Black\",\n\"Hoodie_Black\"\n],\n\"fileNames\": [\n\"MyClothingMod/textures/hoodie/xyz/texture_co.paa\",\n\"MyClothingMod\\\\textures\\\\hoodie\\\\xyz\\\\texture_co.paa\",\n\"MyClothingMod/textures/hoodie/xyz/texture_co.paa\"\n]");
		RegisterClassComment("LBAirdropMarkerConfig", "Only generated when [Airdrop Upgraded](https://steamcommunity.com/sharedfiles/filedetails/?id=1870524790) Mod is installed to control if markers should be added and how they behave");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "enableAirdropMarkers", "Toggle if the Markers should be shown");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "updatePositionWhenDropped", "Update the position to the exact drop location when it's dropped (Airdrop Upgraded has a radius the crate will be dropped)");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "markerForRandomAirdrop", "Add Markers for Airdrops, which spawned random (not player called ones)");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "markerForPlayerCalledAirdrop", "Add Markers for Airdrops called by players");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "nameBeforeDrop", "Name displayed at the rough drop location before the Airdorp arrived");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "nameAfterDrop", "Name displayed after the crate was dropped by the plane");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "icon", "Icon of the Marker, that will be displayed");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "markerColorA", "Alpha (opacity) of the Marker");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "markerColorR", "Red Color of the Marker");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "markerColorG", "Green Color of the Marker");
		RegisterClassVariableComment("LBAirdropMarkerConfig", "markerColorB", "Blue Color of the Marker");
		RegisterClassComment("HelicrashMarkerConfigAG", "Config only generated when the Dynamic Helicrash mod is installed. No extra plugin is needed");
		RegisterClassVariableComment("HelicrashMarkerConfigAG", "enabled", "Enable markers or disable them completely");
		RegisterClassVariableComment("HelicrashMarkerConfigAG", "markerName", "Name of the marker placed for helicrashes");
		RegisterClassVariableComment("HelicrashMarkerConfigAG", "markerIcon", "Icon of the marker");
		RegisterClassVariableComment("HelicrashMarkerConfigAG", "markerColorA", "Alpha (opacity) Color of the Marker");
		RegisterClassVariableComment("HelicrashMarkerConfigAG", "markerColorR", "Red Color of the Marker");
		RegisterClassVariableComment("HelicrashMarkerConfigAG", "markerColorG", "Green Color of the Marker");
		RegisterClassVariableComment("HelicrashMarkerConfigAG", "markerColorB", "Blue Color of the Marker");
	}
}